version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      # Add development-specific environment variables here
      - DEBUG=true
    develop:
      # Create a watch configuration to update the app
      watch:
        # Sync the working directory with the container
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
            - __pycache__/
            - .git/
            - .pytest_cache/
            - .mypy_cache/

        # Rebuild if dependencies change
        - action: rebuild
          path: ./uv.lock
    volumes:
      # Mount the project directory in read-write mode, but exclude the .venv directory
      - ./:/app
      - /app/.venv
    restart: unless-stopped