version: '3.8'

services:
  report-test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app:ro
      - exclude_venv:/app/.venv
    command: /app/.venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped

volumes:
  exclude_venv: